version: "2"
services:
  cwmp:
    build: .
    image: ebits/genieacs
    command: ./bin/genieacs-cwmp
    ports:
     - "7547:7547"
    links:
     - "mongodb"
     - "redis"
    depends_on:
     - "mongodb"
     - "redis"
     
  nbi:
    build: .
    image: ebits/genieacs
    command: ./bin/genieacs-nbi
    ports:
     - "7557:7557"
    links:
     - "mongodb"
     - "redis"
    depends_on:
     - "mongodb"
     - "redis"     

  fs:
    build: .
    image: ebits/genieacs
    command: ./bin/genieacs-fs
    ports:
     - "7567:7567"
    links:
     - "mongodb"
     - "redis"
    depends_on:
     - "mongodb"
     - "redis"

  redis:
    image: redis:alpine

  mongodb:
    image: mongo